### ISSUE TITLE
one attribute error

### ISSUE THREAD

**Issue by nexteve** [Thoxvi/MyCar_python#2]
os.mknod('%s/myurl.dat' % sys.path[0])
AttributeError: 'module' object has no attribute 'mknod'

**Comment by Thoxvi** [comment]
我也不知道这个错误。。。Google查了一下说是
> “mknod是用来创建设备节点，在window下因为文件系统不同创建不了node”
试用Linux跑脚本试试？

**Comment by nexteve** [comment]
# 我把脚本放到国外的VPS上也跑不起来

**Comment by nexteve** [comment]
![image](https://cloud.githubusercontent.com/assets/11267282/17920637/4cc8b8a0-6a08-11e6-965f-ed9867fdf155.png)


![image](https://cloud.githubusercontent.com/assets/11267282/17920601/1354e6b6-6a08-11e6-9939-cc484fc73e9d.png)

**Comment by nexteve** [comment]
http://blog.csdn.net/xiaopangxia/article/details/49908889

**Comment by Thoxvi** [comment]
更新下再跑下试试？
