### ISSUE TITLE
代码103行的更新用户，会导致user文件被清空啊

### ISSUE THREAD

**Issue by sola97** [Thoxvi/MyCar_python#6]
我说怎么用着用着存了好久的用户都没了

**Comment by Thoxvi** [comment]
233333333
不好意思啊不好意思
那段代码没记错的话是清除失效的User
可能出现了小问题。。。





我这里一直跑得很好啊
那些User还可以访问嘛，你试试看？
要是不行的话我有时间再改改233333333
（要是你想改的话可以申请合并啊23333333为司机界做出贡献嘛~）
